/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import domain.DomainController;
import domain.Event;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Gebruiker
 */
public class InputStringFrame extends javax.swing.JFrame {

    int number = -1;
    /**
     * Creates new form AddClickFrame
     */
    public InputStringFrame() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/icon16.png")).getImage());
        jTextFieldInput.requestFocus();
    }
    
    public InputStringFrame(int i, String s, long minp, long maxp)
    {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/icon16.png")).getImage());
        if (minp == maxp)
        {
            this.jTextFieldPause.setText(String.format("%d", minp));
        }
        else
        {
            this.jCheckBoxRandomize.setSelected(true);
            this.jTextFieldMinPause.setText(String.format("%d", minp));
            this.jTextFieldMaxPause.setText(String.format("%d", maxp));
            jTextFieldPause.setEnabled(false);
            jTextFieldPause.setBackground(new Color(153,153,153));
            jTextFieldMinPause.setEnabled(true);
            jTextFieldMinPause.setBackground(new Color(255,255,255));
            jTextFieldMaxPause.setEnabled(true);
            jTextFieldMaxPause.setBackground(new Color(255,255,255));
        }
        jTextFieldInput.setText(s);
        number = i;
        this.jButtonAdd.setText("Modify");
        jTextFieldInput.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPause = new javax.swing.JTextField();
        jTextFieldMinPause = new javax.swing.JTextField();
        jTextFieldMaxPause = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBoxRandomize = new javax.swing.JCheckBox();
        jButtonAdd = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTextFieldInput = new javax.swing.JTextField();
        jLabelInput = new javax.swing.JLabel();
        jLabelFormat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Click");
        setResizable(false);

        jLabel1.setText("Pause:");

        jLabel2.setText("Min. Pause:");

        jLabel3.setText("Max.Pause:");

        jTextFieldPause.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPause.setText("1");
        jTextFieldPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPauseActionPerformed(evt);
            }
        });

        jTextFieldMinPause.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldMinPause.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldMinPause.setText("1");
        jTextFieldMinPause.setEnabled(false);
        jTextFieldMinPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMinPauseActionPerformed(evt);
            }
        });

        jTextFieldMaxPause.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldMaxPause.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldMaxPause.setText("1");
        jTextFieldMaxPause.setEnabled(false);
        jTextFieldMaxPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaxPauseActionPerformed(evt);
            }
        });

        jLabel4.setText("ms");

        jLabel5.setText("ms");

        jLabel6.setText("ms");

        jCheckBoxRandomize.setText("Randomize");
        jCheckBoxRandomize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxRandomizeActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jTextFieldInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInputActionPerformed(evt);
            }
        });

        jLabelInput.setText("Input:");

        jLabelFormat.setText("Only numeric and alphabetical characters allowed.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelInput))
                            .addComponent(jLabelFormat))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPause)
                            .addComponent(jTextFieldMinPause)
                            .addComponent(jTextFieldMaxPause, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxRandomize))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPause, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jCheckBoxRandomize)
                    .addComponent(jLabelInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMinPause, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMaxPause, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelFormat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxRandomizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxRandomizeActionPerformed
        if (jCheckBoxRandomize.isSelected())
        {
            jTextFieldPause.setEnabled(false);
            jTextFieldPause.setBackground(new Color(153,153,153));
            jTextFieldMinPause.setEnabled(true);
            jTextFieldMinPause.setBackground(new Color(255,255,255));
            jTextFieldMaxPause.setEnabled(true);
            jTextFieldMaxPause.setBackground(new Color(255,255,255));
        }
        else
        {
            jTextFieldPause.setEnabled(true);
            jTextFieldPause.setBackground(new Color(255,255,255));
            jTextFieldMinPause.setEnabled(false);
            jTextFieldMinPause.setBackground(new Color(153,153,153));
            jTextFieldMaxPause.setEnabled(false);
            jTextFieldMaxPause.setBackground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jCheckBoxRandomizeActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        long minPause=1, maxPause=1;
        if (jTextFieldInput.getText().length() <= 0)
        {
            JOptionPane.showMessageDialog(null, "You didn't enter any input.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        if (!jCheckBoxRandomize.isSelected() && jTextFieldPause.getText().length() == 0)
            jTextFieldPause.setText("1");
        else if (jCheckBoxRandomize.isSelected() && jTextFieldMinPause.getText().length() == 0)
            jTextFieldMinPause.setText("1");
        else if (jCheckBoxRandomize.isSelected() && jTextFieldMaxPause.getText().length() == 0)
            jTextFieldMaxPause.setText("1");
        else
        {
            if (!jCheckBoxRandomize.isSelected())
            {
                try
                {
                    minPause = Long.parseLong(jTextFieldPause.getText());
                    maxPause = Long.parseLong(jTextFieldPause.getText());
                }
                catch (NumberFormatException e)
                {
                    JOptionPane.showMessageDialog(this, "Pause value is not a number.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            else
            {
                try
                {
                    minPause = Long.parseLong(jTextFieldMinPause.getText());
                    maxPause = Long.parseLong(jTextFieldMaxPause.getText());
                }
                catch (NumberFormatException e)
                {
                    JOptionPane.showMessageDialog(this, "Pause value is not a number.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            if(number == -1)
                DomainController.addEvent(Event.Type.STRING, minPause, maxPause, 0, 0, false, false, false, "", jTextFieldInput.getText(), Color.white, 0, 0);
            else
            {
                DomainController.er.getEventList().get(number).setMinPause(minPause);
                DomainController.er.getEventList().get(number).setMaxPause(maxPause);
                DomainController.er.getEventList().get(number).setString(jTextFieldInput.getText());
            }
            DomainController.hf.updateTable();
        }
        this.dispose();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextFieldInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInputActionPerformed
        if (this.jCheckBoxRandomize.isSelected())
            this.jTextFieldMinPause.requestFocus();
        else
            this.jTextFieldPause.requestFocus();
    }//GEN-LAST:event_jTextFieldInputActionPerformed

    private void jTextFieldPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPauseActionPerformed
        jButtonAdd.doClick();// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPauseActionPerformed

    private void jTextFieldMinPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMinPauseActionPerformed
        this.jTextFieldMaxPause.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMinPauseActionPerformed

    private void jTextFieldMaxPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaxPauseActionPerformed
        jButtonAdd.doClick();// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaxPauseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JCheckBox jCheckBoxRandomize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelFormat;
    private javax.swing.JLabel jLabelInput;
    private javax.swing.JTextField jTextFieldInput;
    private javax.swing.JTextField jTextFieldMaxPause;
    private javax.swing.JTextField jTextFieldMinPause;
    private javax.swing.JTextField jTextFieldPause;
    // End of variables declaration//GEN-END:variables
}
